# Generated by Django 5.1.2 on 2024-10-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='from_user',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mails',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mails',
            name='sent_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mails',
            name='to_user',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
