# Generated by Django 5.1.2 on 2024-11-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_mails_from_user_mails_message_mails_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
